### ISSUE TITLE
Control via sticks only

### ISSUE THREAD

**Issue by muxi1** [suchmememanyskill/Payload_Launcher#10]
Hello @suchmememanyskill,
Is this intended so that the Payload Launcher 3.0.0 can only be controlled with the sticks? I found it convenient to be able to navigate with the Direction keys as well.

**Comment by suchmememanyskill** [comment]
Hi, yeah i never really re-implemented that. I'll see if i can fix that soon-ish. (Should be a 2 line change)

**Comment by muxi1** [comment]
That would be great! Thanks a lot.

**Comment by suchmememanyskill** [comment]
added in commit 0e353d1

**Comment by muxi1** [comment]
Will this change come with the next release?

**Comment by suchmememanyskill** [comment]
yes, or you can build the application yourself to get it now. Will keep the issue open until i make a release

**Comment by muxi1** [comment]
Unfortunately my knowledge is not sufficient for this, so I have to wait until the next release. Thanks for adding this feature!

**Comment by ghost** [comment]
@muxi1 You can try this in the meantime. Pad navigation working fine. Compiled from master as of right now.
[Payload_Launcher.zip](https://github.com/suchmememanyskill/Payload_Launcher/files/4075208/Payload_Launcher.zip)

**Comment by muxi1** [comment]
@TehPsychedelic Many thanks for compiling!

**Comment by ZaydelSenpai** [comment]
Thanks a lot for this implementation! Payload Laucher is awesome! Are you gonna close this issue? :)

**Comment by suchmememanyskill** [comment]
Sure.
