### ISSUE TITLE
Crashes on latest fw 12.0/atmosphere 0.19.x

### ISSUE THREAD

**Issue by metal1one** [suchmememanyskill/Payload_Launcher#12]
I believe it needs to be recompiled due to:

Please Note: 12.0.0 added a new protocol for IPC ("tipc"), which has been freshly reimplemented in its entirety.
It is possible there may be as of yet unfound issues; if there are, please send the appropriate crash reports to SciresM (SciresM#0524 on discord).
Homebrew which uses atmosphere extensions (including the mitm API) will need to be re-compiled in order to function on 0.19.0.

**Comment by suchmememanyskill** [comment]
this is not the issue. But it definitely needs to be recompiled. The source won't compile anymore, though. I'll think about remaking it

**Comment by suchmememanyskill** [comment]
i've managed to recompile it. I'll release it in a bit
