### ISSUE TITLE
Not working with atmosphere 1.2.3

### ISSUE THREAD

**Issue by ghost** [suchmememanyskill/Payload_Launcher#13]
After i updated my copy of atmos cfw, this your tool stopped working.

When possible, update it.

Thanks.

**Comment by suchmememanyskill** [comment]
I've tried for a bit but the random ass changes to hid in dkp make me unable to just easily update it, i have to change all hid code. Sigh. I'll try to update it at some point

**Comment by suchmememanyskill** [comment]
I feel a little embarrassed as i got it working a minute later. Release soon
