### ISSUE TITLE
Suggestion - use /bootloader/payloads

### ISSUE THREAD

**Issue by hippydave** [suchmememanyskill/Payload_Launcher#2]
hekate already uses this path, so it's a chance to not have another duplicate set of payloads.
I made this change for my own build and it's working great, thanks for the useful app.

**Comment by 16BitWonder** [comment]
I actually ended up doing the same thing in a fork.
Would definitely be nice to keep a centralized payload location between homebrew applications and hekate.

**Comment by suchmememanyskill** [comment]
Sounds like an idea, maybe it's a better idea to let the user select their payload folder on first boot of the app? (Like get a row of possible payload folders)

**Comment by suchmememanyskill** [comment]
Also as a note, people also use argonx for example for payloads, so those people will start complaining if i would make it bootloader/payloads for example

**Comment by hippydave** [comment]
Yep configurable path sounds ideal, whether you select it from the app or just write it in a config file, all good.

**Comment by suchmememanyskill** [comment]
Should be implemented now

**Comment by suchmememanyskill** [comment]
https://github.com/suchmememanyskill/Payload_Launcher/releases/tag/1.1.0
