### ISSUE TITLE
Suggestion - Autorun Payloads when a defined button is held

### ISSUE THREAD

**Issue by Shinygati** [suchmememanyskill/Payload_Launcher#3]
Figured it would be a nice feature to have for payloads to run automatically if set by the user or with a button held down, would make it much faster for rebooting between cfw's such as atmosphere or reinx and so on.

**Comment by suchmememanyskill** [comment]
You mean autoboot in general or just when a button is held on boot? I guess there's the "favourite" payload function now, where you press Y on a payload to favourite it, and X to quicklaunch it.

I guess i might be able to set an autoboot with a 3 sec delay unless a button is pressed.

**Comment by suchmememanyskill** [comment]
I dont think this will become a feature i'll implement (mostly as i don't have a lot of time atm)

**Comment by Shinygati** [comment]
Sorry didn't see any replies until now, but i was talking about having it launch a payload automatically without any user input, maybe enable it for favorited payloads?

**Comment by suchmememanyskill** [comment]
I'll keep that in mind for a future update
