### ISSUE TITLE
GPL Violation

### ISSUE THREAD

**Issue by SciresM** [suchmememanyskill/Payload_Launcher#5]
As you acknowledge in the readme, this uses code taken from Atmosphere.

Atmosphere is licensed GPLv2 -- thus, your program must also be licensed GPLv2, the MIT license is not valid.

Please relicense :)

**Comment by SciresM** [comment]
You're probably actually not in violation, since you include the separate license...sketchy though.

**Comment by suchmememanyskill** [comment]
Think that fixes it, thanks for pointing it out

**Comment by SciresM** [comment]
Yep, lgtm.
