### ISSUE TITLE
Update for 9.0 - libnx 2.5

### ISSUE THREAD

**Issue by danfozzy** [suchmememanyskill/Payload_Launcher#7]
Hoping this isn't abandoned, can a release be pushed to support the latest libnx

**Comment by SuperMario20** [comment]
ye

**Comment by 16BitWonder** [comment]
It can already be built with the latest libnx.
Just clone the repository and make.

**Comment by suchmememanyskill** [comment]
Somehow didn't get a notification for this: planning on rewriting it in general as the code can be improved. I'll look into it this evening

**Comment by suchmememanyskill** [comment]
https://github.com/suchmememanyskill/Payload_Launcher/releases/tag/2.0.0 grab it while it's hot

**Comment by danfozzy** [comment]
Thank you!
